"""兼容层：保留历史导入路径 `service.config_service`。"""

from __future__ import annotations

from .config import (
    AppConfig,
    ConfigError,
    ConfigService,
    CpaConfig,
    DEFAULT_GMAIL_SCOPES,
    DEFAULT_HTTP_IMPERSONATE,
    DEFAULT_HTTP_USER_AGENT,
    DEFAULT_OPENAI_REGISTER_CLIENT_ID,
    DEFAULT_QWEN_REGISTER_CLIENT_ID,
    DuckMailConfig,
    FirefoxRelayConfig,
    FreeMailConfig,
    GmailApiConfig,
    GmailConfig,
    GrokRegisterConfig,
    HeroSmsConfig,
    HttpConfig,
    LuckMailConfig,
    OpenAIHeroSmsConfig,
    OpenAIRegisterConfig,
    QwenRegisterConfig,
)

__all__ = [
    "AppConfig",
    "ConfigError",
    "ConfigService",
    "CpaConfig",
    "DEFAULT_GMAIL_SCOPES",
    "DEFAULT_HTTP_IMPERSONATE",
    "DEFAULT_HTTP_USER_AGENT",
    "DEFAULT_OPENAI_REGISTER_CLIENT_ID",
    "DEFAULT_QWEN_REGISTER_CLIENT_ID",
    "DuckMailConfig",
    "FirefoxRelayConfig",
    "FreeMailConfig",
    "GmailApiConfig",
    "GmailConfig",
    "GrokRegisterConfig",
    "HeroSmsConfig",
    "HttpConfig",
    "LuckMailConfig",
    "OpenAIHeroSmsConfig",
    "OpenAIRegisterConfig",
    "QwenRegisterConfig",
]
